FROM debian:jessie

#Change source liste
RUN rm /etc/apt/sources.list
RUN echo "deb http://httpredir.debian.org/debian jessie main non-free" > /etc/apt/sources.list
RUN echo "deb http://httpredir.debian.org/debian jessie-updates main" >> /etc/apt/sources.list
RUN echo "deb http://security.debian.org jessie/updates main" >> /etc/apt/sources.list
# persistent / runtime deps
RUN apt-get update && apt-get install -y ca-certificates curl librecode0 libsqlite3-0 libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*

##<autogenerated>##
RUN apt-get update && apt-get install -y apache2-bin apache2.2-common apache2-mpm-worker libapache2-mod-fastcgi --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y php5-fpm php-gettext php5 php5-common php5-curl php5-gd php5-imagick php5-intl php5-json php5-mcrypt php5-mysqlnd php5-readline php5-tidy php5-xmlrpc

RUN rm -rf /var/www/html && mkdir -p /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html && chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html

# Apache + PHP requires preforking Apache for best results
RUN a2dismod mpm_event && a2enmod mpm_worker

##</autogenerated>##

ENV GPG_KEYS 0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3
RUN set -xe \
	&& for key in $GPG_KEYS; do \
		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
	done

##<autogenerated>##
WORKDIR /var/www/html

RUN groupadd -r dis && useradd -r -g dis dis
EXPOSE 80
ENTRYPOINT service apache2 start && /bin/bash
#CMD ["apache2-foreground"]
##</autogenerated>##
